import Head from 'next/head'
import { useState } from 'react'
import { getServerSideProps } from './api/todos'

export default function Home({todos}) {
  // estamos iniciando todosState com conteúdo vindo do server side (NodeJS)
  const [todosState, setTodosState] = useState(todos)

 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Todos </h1>
      {
        todosState?.length === 0 ? (<div> Loading ... </div>) : 
        (
          todosState.map(todo => {
            return (
              <div key={todo.id}>
                <p> {todo.id} : {todo.title} </p>
              </div>
            )
          }
          ))
      }
    </>
  )
}

export { getServerSideProps }